[HOPSWORKS-2828] Add scikit-learn_version attribute
logicalclocks/conda-chef pull request #127
Opened 2021-12-28 16:31 UTC by javierdlrm

2021-12-29 13:17 UTC, robzor92 requested changes

2021-12-29 13:17 UTC, robzor92 commented on attributes/default.rb
> +default['scikit-learn']['version']                = "0.22.2.post1"
Can you add a comment https://github.com/logicalclocks/docker-images/blob/327e9cb07c098dd48fabe60fa5b9dc0dceea7b50/base_image/python38/env.yml#L66 that we also need to update the version in conda-chef whenever we update it in the env.yml?

2021-12-29 13:50 UTC, javierdlrm commented on attributes/default.rb
> +default['scikit-learn']['version']                = "0.22.2.post1"
Done

2022-01-03 12:20 UTC, robzor92 approved these changes

2022-01-27 19:47 UTC, merged